pragma solidity ^0.5.12;
import "./StamperFactory.sol";

/// @title DAO Contract to nominate and govern climate policies based on the CAT (carboTag) network.
/// @author Bertrand Williams-Rioux
/// @notice Use this contract to create new carbon management token programs (i.e. emission certificates, carbon management assets, offset credits)
/// @dev <docment-me>
contract COG{
	mapping (address => bool) public governor;
	address public owner;
	address public carboTagAddr;
  	modifier onlyOwner () {  //added some security
  	  require(msg.sender == owner, 'Only the contract owner can do that');
  	  _;
  	}
  	modifier onlyGovernor () {    //added some governance
  	  require(governor[msg.sender] == true);
  	  _;
  	}

  	constructor(address payable _owner) public {
  		owner = _owner;
  		carboTagAddr = msg.sender; // This contract should be generated by request from a CAT newtork?
  	    governor[owner]=true;
  	    StamperFactory stamperFactory = new StamperFactory(msg.sender,owner);
  	}

  	function addGovernor(address _target)  
  	  public 
  	  onlyOwner()
  	{
  	  governor[_target]=true;
  	}

}